##### Beginning of file

############################################################################

branches:
    only:
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

env:
    global:
        - JULIA_DEBUG="all"
    matrix:
        - JOB="[,)" JULIA_VER="1.1"

git:
    depth: 99999999

language: bash

matrix:
    allow_failures:
    - os: osx
    fast_finish: true

notifications:
    email:
        on_success: never # default: change
        on_failure: always # default: always

os:
    - linux
    - osx

############################################################################

before_install: ./ci/travis/before_install.sh
install: ./ci/travis/install.sh
before_script: true
script: ./ci/travis/script.sh
after_script: true

############################################################################

##### End of file
