block_labels = [ "DO NOT MERGE" ]

delete_merged_branches = true

status = [
    "continuous-integration/travis-ci/push",
]

timeout_sec = 57600

[committer]
name = "BCBI Bot"
email = "bcbi-git@brown.edu"
